=== Capybara-Enjoyer/statnice/statnice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:element name="statnice">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="komisar" type="komisarType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="komise" type="komiseType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="posledniUpdate" type="xs:date" use="optional" />
        </xs:complexType>
        <xs:unique name="uniqueJmenoTituly">
            <xs:selector xpath="komisar" />
            <xs:field xpath="@jmeno" />
            <xs:field xpath="@tituly" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="komisarType">
        <xs:sequence>
            <xs:element name="otazka" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="jmeno" type="xs:string" use="required" />
        <xs:attribute name="tituly" type="xs:string" use="optional" />
    </xs:complexType>


    <xs:complexType name="komiseType">
        <xs:sequence>
            <xs:element name="komisar" type="komisarInGroupType" minOccurs="3" maxOccurs="3" />
            <xs:element name="otazka" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="komisarInGroupType">
        <xs:attribute name="jmeno" type="xs:string" use="required" />
        <xs:attribute name="tituly" type="xs:string" use="optional" />
    </xs:complexType>

</xs:schema>

=== Capybara-Enjoyer/statnice/statnice.xml
<?xml version="1.0" encoding="UTF-8"?>
<statnice
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="statnice.xsd"
    posledniUpdate="2025-06-17"
>
    <komisar jmeno="Svatá Vlasta" tituly="doc. Ing., CSc.">
        <otazka>Co je proces, procesní řízení, modely procesů, jejich úrovně, notace pro modelování procesů?</otazka>
        <otazka>Jaké existují modely dodávek služeb ERP systémů?</otazka>
        <otazka>Jaké je workflow použité metodiky, popište jednotlivé kroky.</otazka>
        <otazka>Zhlediska teorie rizik, znáte nějaký jiný přístup, kde se nepracuje se zranitelností, kterou jste použil z práce.</otazka>
        <otazka>Věděl byste co je mapa rizik?</otazka>
        <otazka>Píšete o tom, že lze použít kvalitativní i kvantitativní metody, mohou být i jiné přístupy? Dejte příklad.</otazka>
        <otazka>Jak rozumíte IT Governance?</otazka>
    </komisar>
    <komisar jmeno="Černý Jan" tituly="PhDr., Ph.D.">
        <otazka>Co je etika a informační etika?</otazka>
    </komisar>
    <komisar jmeno="Strnad Pavel" tituly="Ing., Ph.D.">
        <otazka>Vysvětlete Pojmy overfitting a underfitting?</otazka>
        <otazka>Jaké jsou typy strojového učení a rozdíly mezi nimi?</otazka>
        <otazka>Popište prosím základní rozdíl mezi strojovým učením s učitelem a bez učitele?</otazka>
        <otazka>Jaký je rozdíl mezi pojmy overfitting a underfitting?</otazka>
        <otazka>Základní rozdíl mezi strojovým učením s učitelem a bez učitele?</otazka>
        <otazka>Jaký je rozdíl mezi overfitting a underfitting?</otazka>
        <otazka>Jaké byste použil tři základní přístupy k anonymizací své vlastní identity?</otazka>
        <otazka>Jak byste postupoval, kdybyste se chtěl proti dvěma druhům útokům zabezpečit? Druh útoku si vyberte.</otazka>
        <otazka>Jaké typy dat znáte? A jaké jsou dnes používané pro přenos dat mezi systémy?</otazka>
        <otazka>Jakým způsobem jste se zamýšlel nad bezpečností dat, která vkládají studenti při registraci?</otazka>
        <otazka>Můžete nám představit koncept IT Governance v rámci firemní praxe? Představte nám v této souvislosti Balanced Scorecard a jeho užití</otazka>
        <otazka>Myslíte si, že LLM mají vědomí? A proč ano/ne?</otazka>
        <otazka>Jaké jsou moderní trendy v IT?</otazka>
        <otazka>Jak se v daném řešení byly realizovány problémy bezpečnosti?</otazka>
        <otazka>Navržené řešení běží on premise nebo v cloudu?</otazka>
    </komisar>
    <komisar jmeno="Pour Jan" tituly="doc. Ing., CSc.">
        <otazka>Co je podstatou byznys informatiky?</otazka>
        <otazka>Jaké jsou hlavní nároky a problémy spojené s analytickými úlohami?</otazka>
        <otazka>Co je podstatou Big Data?</otazka>
        <otazka>Co je podstatou Data Lake a jak se řídí jeho provoz?</otazka>
        <otazka>Co je náplní podnikového informačního systému?</otazka>
        <otazka>Jaké typy aplikací se vyskytují v podnikové informatice?</otazka>
        <otazka>Jaké jsou problémy spojené s implementací ERP?</otazka>
        <otazka>Podnikové informační systémy - aplikace prediktivní analytiky?</otazka>
        <otazka>Jaké jsou faktory ovliňují řešení úlohy prediktivní analytiky?</otazka>
        <otazka>Co je IT Governance, jak ho lze využít ve firmně praxi?</otazka>
        <otazka>Co lze použít z UML jazyka pro návrh webu?</otazka>
        <otazka>Jaké jsou hlavní modely pro řízení informatiky ve firmě?</otazka>
        <otazka>Řízení informatiky a podpora byznysu, hlavní funkce a klíčové problémy?</otazka>
        <otazka>Co se rozumí kvalitní podporou byznysu firmy?</otazka>
        <otazka>Jaká je podpora byznysu vzhledem k různým typům IT aplikací a nástrojů?</otazka>
        <otazka>Integrace IT. Jaké jsou cíle, základní principy systémové integrace?</otazka>
        <otazka>Jaké jsou úrovně integrace v IS?</otazka>
        <otazka>Jaké jsou problémy spojené se systémovou integrací?</otazka>
        <otazka>Co je podstatou podnikové analytiky a specificky business intelligence?</otazka>
        <otazka>Kde jsou hlavní problémy spojené s řešení úloh business intelligence?</otazka>
        <otazka>Jaký je problém spojený s kooperací s uživateli v BI?</otazka>
        <otazka>Podnikové informační systémy, co je podstatou a obsahem?</otazka>
        <otazka>Jaké jsou klíčové typy aplikací v podnikové informatice?</otazka>
        <otazka>Jaké jsou hlavní problémy spojené s řešením aplikací podnikové informatiky?</otazka>
        <otazka>Jaké jsou problémy řešení a provozu eShopu?</otazka>
        <otazka>Jaké jsou aplikace orientované na externí vztahy?</otazka>
        <otazka>Modelování podnikových systémů, jaké jsou hlavní principy?</otazka>
        <otazka>Kde jsou klíčové problémy s modelováním podnikových procesů?</otazka>
        <otazka>Co je principem datových modelů?</otazka>
        <otazka>Jakými znalostmi musí být vybaven analytik pro modelování informačních systémů?</otazka>
        <otazka>Řízení projektů IS/ICT, jaký je obsah a funkce?</otazka>
        <otazka>Jaké jsou hlavní modely uplatňované v řízení projektů?</otazka>
        <otazka>Jaké jsou aktuální hlavní problémy řízení projektů?</otazka>
        <otazka>Řízení informatiky a podpora byznysu, jaké jsou hlavní problémy v řízení IT?</otazka>
        <otazka>Co se rozumí termínem business – IT aligment?</otazka>
        <otazka>Jaké jsou možnosti a příklady podpory byznysu z pohledu IT?</otazka>
        <otazka>Co by mělo být jako znalostní základ analytika při tvorbě aplikací IT?</otazka>
        <otazka>Modelování podnikových systémů, podstata, problémy</otazka>
        <otazka>Jaké jsou problémy spojené s modelováním procesů?</otazka>
        <otazka>Jaké jsou principy a problémy datového modelování?</otazka>
        <otazka>Řízení informatiky, jaký je obsah a hlavní principy?</otazka>
        <otazka>Lze shrnout hlavní efekty navrhovaného řešení?</otazka>
        <otazka>Co je obsahem IT ekonomiky?</otazka>
        <otazka>Business intelligence, jaké jsou hlavní principy a problémy analytických úloh?</otazka>
        <otazka>Co se rozumí konsolidaci dat?</otazka>
        <otazka>Jaké jsou rozdíly mezi BI a SBI?</otazka>
        <otazka>Základní charakteristiky firmy působící na trhu IS/CT?</otazka>
        <otazka>Specifické nároky na řízení informatické firmy?</otazka>
        <otazka>Jaké jsou hlavní problémy v analýze a modelování procesů?</otazka>
        <otazka>Integrace v informačních systémech, principy, problémy?</otazka>
        <otazka>Jaké jsou různé možnosti integrace apllikací v IS?</otazka>
        <otazka>Co je systémová integrace?</otazka>
    </komisar>
    <komisar jmeno="Sudzina František" tituly="Mgr. et Mgr. Ing., Ph.D.">
        <otazka>Jaké jsou problémy s kvalitou dat?</otazka>
        <otazka>Jaký druh databází byste použil pro ukládání informací předcházejících dopravní nehodě?</otazka>
        <otazka>Jaká existují šifrování?</otazka>
        <otazka>Jaké protokoly se používají na síťové vrstvě?</otazka>
        <otazka>Co je SSH a jak se využívá?</otazka>
        <otazka>V čem je rozdíl u supervised a unsupervised training?</otazka>
        <otazka>Řízení kvality vývoj SW (testování).</otazka>
        <otazka>Ukládání a vyhledávání textových informace, co byste o tom mohl říci a jak to souvisí s tématem Vaší práce?</otazka>
        <otazka>Jaké budou rozdíly v uplatňování šifrování?</otazka>
        <otazka>Jaké modely lze použít pro datové modelování?</otazka>
        <otazka>Jaké typy/klasifikaci požadavků na SW znáte?</otazka>
        <otazka>Co je to prototyp?</otazka>
        <otazka>V čem spočívá rozdil mezi TCP a UDP?</otazka>
        <otazka>Co jsou to regulární výrazy?</otazka>
        <otazka>Co je API v řešení aplikací?</otazka>
        <otazka>Co je TCP a UDP?</otazka>
        <otazka>Jaké jsou metodiky řízení kvality software?</otazka>
        <otazka>Jaká je podstata řízení testy?</otazka>
        <otazka>Jaké jsou návrhové vzory pro řešení software?</otazka>
        <otazka>Na které vrstvě ISO OSI modelu jsou TCP a UDP?</otazka>
        <otazka>Jaké jsou výhody využití databází v porovnání s tabulkami např. v Excelu?</otazka>
        <otazka>V čem se liší protokoly TCP a UDP a na jaké vrstvě ISO/OSI modelu se nacházejí?</otazka>
    </komisar>
    <komisar jmeno="Vojíř Stanislav" tituly="Ing. et Ing., Ph.D.">
        <otazka>Jaké jsou protokoly na aplikační úrovni sítí?</otazka>
        <otazka>Co je podstatou digitálního podpisu, jaké jsou certifikační autority?</otazka>
        <otazka>Jaké zdroje se generativní AI učí? Jsou nějaké regulace týkající se zpracování soukromých dokumentů uživatelů pomocí AI?</otazka>
        <otazka>Co je to "právo na zapomenutí" a jak funguje?</otazka>
        <otazka>Jak funguje sledování uživatelů na internetu?</otazka>
        <otazka>Znáte nějaké nástroje pro bezpečnější pohyb na internetu?</otazka>
        <otazka>Co je to VPN?</otazka>
        <otazka>Jak funguje spojení mezi vaším serverem a VPN z hlediska bezpečnosti?</otazka>
        <otazka>Jaké jsou možnosti ověření uživatele při přihlašování k VPN serveru?</otazka>
        <otazka>Jak fungují certifikáty? Jak lze získat certifikát?</otazka>
        <otazka>Jakým způsobem se dá zkoumat návštěvnost diskuzních fór na webu? Co sleduje Google Analytics? Jakým způsobem Google Analytics sleduje uživatele? Jak se pozná, že jde o konkrétního uživatele?</otazka>
        <otazka>Pokud vyvíjíte pro mobilní zařízení — jaké jsou výhody implementace v podobě nativní aplikace oproti webové či hybridní podobě?</otazka>
        <otazka>Jazykové modely jsou jedním z typů použití Al. Znáte nějaké jiné modely patřící do oblasti Al / strojového učení?</otazka>
        <otazka>Mohl byste uvést nějaký konkrétní problém řešitelný pomocí stromů?</otazka>
    </komisar>
    <komisar jmeno="Buchalcevová Alena" tituly="prof. Ing., Ph.D.">
